################################################################
# allies      | list   | list of org handles that are allies   #
# ------------------------------------------------------------ #
# enimies     | list   | list of org handles that are enimies  #
# ------------------------------------------------------------ #
# rsi_org_sid | string | the org's handle running this bot     #
################################################################
allies = []
ally_role = "ally"
enimies = []
rsi_org_sid = "MYORG"

################################################################
# log                                                          #
# ------------------------------------------------------------ #
# debug | bool | enable debug logs. false by default           #
# cli   | bool | log to the cli. false by default              #
################################################################
[LOG]
debug = false
cli = false

################################################################
# mongo                                                        #
# ------------------------------------------------------------ #
# host     | string | The host of the mongo server             #
# port     | string | port of the mongo server                 #
# database | string | name of the database. defaults to "org"  #
################################################################
[mongo]
host = "localhost"
port = "27017"
database = "MyOrg"

################################################################
# features.events                                              #
# ------------------------------------------------------------ #
# enabled    | bool         | false | enable events            #
################################################################
[features.monitor]
enabled = false

################################################################
# features.bank                                                #
# ------------------------------------------------------------ #
# holders | string array | The bank holders                    #
################################################################
[features.bank]
enabled = false
holders = ["92030047161970688"]

################################################################
# features.attendance                                          #
# ------------------------------------------------------------ #
# enabled       | bool         | false | enable attendance     #
# allowed_roles | string array |       | Role names that can   #
#               |              |       | take attendance       #
# channel_id    | string       |       | Channel id to post    #
#               |              |       | attendance records to #
################################################################
[features.attendance]
enabled = false
allowed_roles = []
channel_id = "000000000000000004"

################################################################
# discord                                                      #
# ------------------------------------------------------------ #
# client_id     | string | discord application client id       #
# client_secret | string | discrod application client secret   #
# guild_id      | string | guild id to use for this tool       #
################################################################
[discord]
client_id = "givenclientid"
client_secret = "supersecretapplicationcode"
guild_id = "guildid"
