name: Docker Image CI
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build the Docker image from"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check out the repository
        run: docker build . --file Dockerfile --tag sol-bot:${{ github.sha }}
      - name: Tag the Docker latest image
        run: docker tag sol-bot:${{ github.sha }} ghcr.io/sol-armada/sol-bot:latest
      - name: Tag the Docker version image
        run: docker tag sol-bot:${{ github.sha }} ghcr.io/sol-armada/sol-bot:${{ github.ref_name }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push the Docker images to GitHub Container Registry
        run: |
          tag=${{ github.ref_name }}
          if [[ "$tag" =~ ^v[0-9]+.[0-9]+.[0-9]+$ ]]; then
            docker push ghcr.io/sol-armada/sol-bot:latest
          fi
          docker push ghcr.io/sol-armada/sol-bot:${{ github.ref_name }}
